import { Link, useLocation } from "react-router-dom";
import { ArrowRight, CircleHelp, Mail, ShieldCheck } from "lucide-react";
import HubLayout from "../../components/Hub/HubLayout";

const questions = [
  ["Where should I start?", "Start with Web Creator if you want to build websites, C++ Developer if you enjoy logic and systems, or Algorithm & Data Structures for visual problem solving. Choose a path, open the first world, and follow the lessons in order."],
  ["How does progress work?", "Lessons and challenges save progress in this browser. Complete each world's required work to unlock the next one. Your overview and achievements use those saved results. Clearing your browser data or using another device will not carry over this local progress."],
  ["Do I need to install anything?", "You can read lessons, explore worlds and solve the practice arena challenges right in your browser. All interactive 3D visualizations run seamlessly in modern web browsers."],
  ["How do parent and student accounts connect?", "Create a parent account to receive an invitation code. Use that code when registering the student account. During local development, linked accounts and learning progress are available in the same browser. Cross-device family reporting requires the backend service."],
  ["Why is a world locked?", "Worlds build on one another. Finish the previous world's lessons and challenges to unlock the next. You can always return to completed lessons to practice."],
  ["Can I explore before creating an account?", "Yes. Use the student preview from the login page or the learning workspace. Preview progress stays in a separate demo profile on this browser and is not transferred into a registered account."],
  ["How are points and achievements awarded?", "Complete lesson activities to earn their listed XP. Each practice arena challenge earns 25 XP once, and each curriculum lesson earns listed XP once. Repeating the same activity is great practice, but doesn't add duplicate points."],
];
export default function Help() {
  const recovery = useLocation().pathname === "/forgot-password";
  return <HubLayout title={recovery ? "Account help" : "Help & support"}><div className="hub-heading"><div><span className="hub-eyebrow"><CircleHelp size={13} /> A LITTLE GUIDANCE GOES A LONG WAY</span><h1>{recovery ? "Let's get you back on track." : "Questions are where learning starts."}</h1><p>{recovery ? "Help with accessing your CodeLand account." : "Everything you need for a confident start to your adventure."}</p></div></div>{recovery && <section className="hub-panel" style={{ marginBottom: 25 }}><ShieldCheck size={26} color="#b59aff" /><h2 className="hub-spaced">Account recovery</h2><p className="hub-lesson-copy">Password recovery email isn't connected yet. Contact CodeLand support for help with your account. Never include your password in a support message.</p><div className="hub-flex"><a className="hub-btn primary" href="mailto:ba32397@gmail.com?subject=CodeLand%20account%20help"><Mail size={15} />Contact support</a><Link className="hub-btn ghost" to="/login">Back to log in</Link></div></section>}<section className="hub-panel"><h2>Good to know</h2>{questions.map(([question, answer]) => <details className="hub-faq" key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section><div className="hub-bottom-callout"><Mail size={26} /><div><h3>Still need a hand?</h3><p>Tell us what you were trying to do and where you got stuck.</p></div><a className="hub-btn small ghost" href="mailto:ba32397@gmail.com?subject=CodeLand%20support">Contact support <ArrowRight size={14} /></a></div></HubLayout>;
}
